#!/usr/bin/env bash
set -eo pipefail

main() {
	if ! command -v saq &> /dev/null; then
		echo "saq could not be found" >&2
		echo "get it at https://github.com/diamondburned/saq" >&2
		exit 1
	fi

	saq "$@" \
		-s localhost:8391 \
		-t localhost:8300 \
		-x ./server/frontend/package-lock.json \
		-x ./server/frontend/static \
		-- "$BASH_SOURCE" build_and_run
}

build_and_run() {
	go generate ./...
	go build -o ${TMPDIR:-/tmp}/february-frenzy
	exec ${TMPDIR:-/tmp}/february-frenzy
}

case "$1" in
	build_and_run)
		build_and_run
		;;
	*)
		main "$@"
		;;
esac
