// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type HackathonSubmission struct {
	TeamName           string
	SubmittedAt        DateTime
	ProjectUrl         string
	ProjectDescription sql.NullString
	Category           string
	WonRank            sql.NullInt64
}

type Team struct {
	TeamName         string
	CreatedAt        DateTime
	InviteCode       string
	AcceptingMembers bool
}

type TeamMember struct {
	TeamName string
	Username string
	JoinedAt DateTime
	IsLeader bool
}

type TeamPoint struct {
	TeamName string
	AddedAt  DateTime
	Points   float64
	Reason   string
}

type TeamSubmitAttempt struct {
	TeamName    string
	ProblemID   string
	SubmittedAt DateTime
	Correct     bool
	SubmittedBy sql.NullString
}
