// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Team struct {
	TeamName         string
	CreatedAt        time.Time
	InviteCode       string
	AcceptingMembers bool
	Points           int64
}

type TeamMember struct {
	TeamName string
	UserName string
	JoinedAt time.Time
	IsLeader bool
}

type TeamSubmitAttempt struct {
	TeamName    string
	ProblemID   string
	SubmittedAt time.Time
	Correct     bool
}
